### ISSUE TITLE
PIP Install

### ISSUE THREAD

**Issue by PetrochukM** [lmnt-com/haste#11]
With PyTorch, I am used to installing via `pip` without needing to build the library. Would that be possible to support? I don't have too much experience with building libraries, which is why I see this as important. 

It also makes it much easier to work with this library on a laptop, which is my primary development environment.

**Comment by sharvil** [comment]
It's possible but quite a bit of work for each release. Is there a particular issue you're running into when building the code? I may be able to help you get past that.

**Comment by flavioschneider** [comment]
Is it possible to install haste in google colab?

**Comment by sharvil** [comment]
Yes! See https://colab.research.google.com/drive/1hzYhcyvbXYMAUwa3515BszSkhx1UUFSt for an example of using Haste with TensorFlow on Colab.

**Comment by PetrochukM** [comment]
The specific issue was a workflow issue. 

Our team needed a reproducible approach to installing this repository on both our Macbooks and the cloud machines. We handle all of our dependency management with `pip`.
