### ISSUE TITLE
Install fails on AWS DLAMI v. 29.0

### ISSUE THREAD

**Issue by amurashov** [lmnt-com/haste#16]
As you know the code does not work on K80 for me now, so I went on to experiment on Amazon EC2.

I have launched a p2.xlarge instance with Deep Learning AMI (Amazon Linux 2) Version 29.0.

I executed following commands:

source activate tensorflow2_p36
git clone https://github.com/lmnt-com/haste
cd haste
make haste_tf
pip install haste_tf-*.whl
python
import haste_tf

Now I get the following error:

-----
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/haste_tf/__init__.py", line 22, in <module>
    from .gru import GRU
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/haste_tf/gru.py", line 32, in <module>
    LIB = tf.load_op_library(pkg_resources.resource_filename(__name__, 'libhaste_tf.so'))
  File "/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory
-----

Experiments with adding things to LD_LIBRARY_PATH all failed. As a matter of fact, LD_LIBRARY_PATH already contains cuda libs with cudaart.so.10.0 there.

**Comment by amurashov** [comment]
same error with:

Deep Learning AMI (Ubuntu 18.04) Version 29.0

no idea why:

import os
print(os.environ['LD_LIBRARY_PATH'])

/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/usr/local/cuda-10.1/lib:/usr/local/cuda-10.1/efa/lib:/opt/amazon/efa/lib:/opt/amazon/efa/lib64:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/::/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow

----

I think it compiles with wrong CUDA - 10.0 while TF clearly uses 10.1 in this setup, and 10.0 is NOT on the PATH of default TF installation. I think HASTE takes 10.0 as it is the default CUDA dir in /usr/local/cuda -> which points to cuda-10.0, not cuda-10.1.

Is it possible to pull CUDA version from TF during the make haste_tf run like you do with include directories may be?

**Comment by amurashov** [comment]
Actually adding /usr/local/cuda-10.0/lib64 to the LD_LIBRARY_PATH solved it.

**Comment by amurashov** [comment]
Or - laternatively - changing /usr/local/cuda to point to /usr/local/cuda-10.1 instead of /usr/local/cuda-10.0 at haste compile time.

**Comment by sharvil** [comment]
`/usr/local/cuda` is the standard path for the "current" installation of CUDA Toolkit. If multiple versions of CUDA Toolkit are present, `/usr/local/cuda` should point to the one you'd like to use. If Amazon's DLAMI builds TensorFlow against 10.1 but points `/usr/local/cuda` to 10.0, that's a misconfiguration on their part.

Regardless, I've made it possible to override the CUDA Toolkit path to build against without having to modify the `Makefile`. You can either export the `$CUDA_HOME` environment variable or specify it on the command-line while building Haste:
```
CUDA_HOME=/usr/local/cuda-10.1 make
```

Thanks for pushing through these issues and reporting them, @amurashov. I appreciate it.

**Comment by sharvil** [comment]
There are two issues with detecting which version of CUDA TensorFlow is built against. First, there's no great way to do that as far as I can tell. The second is that Haste is multi-framework and PyTorch/TensorFlow could be built against different CUDA versions.

I think making it easier for the user to choose the CUDA version to build against is the best I can do here. Closing this out since there's no further action I can take on my part. Please re-open if you have suggestions on what else I could do.
