### ISSUE TITLE
Problem installing on Ubuntu 20.04, tensorflow 2.2

### ISSUE THREAD

**Issue by doubleapple123** [lmnt-com/haste#19]
I'm getting an issue while installing using make haste_tf or just make 

File "setup.py", line 54
    with open(f'tf/_version.py', 'wt') as f:
                              ^
SyntaxError: invalid syntax
make: *** [Makefile:61: haste_tf] Error 1

not sure what the problem might be here, I can train models using gpu in tensorflow so I don't think it's a cuda or tensorflow problem but I'm not sure.

**Comment by sharvil** [comment]
Which version of Python are you using? Looks like there's an issue with the f-string.

**Comment by doubleapple123** [comment]
python2.7, is there a way to try installing with a different version of python?

**Comment by sharvil** [comment]
Haste requires Python 3.5 or above. Python 2 is [end-of-life](https://www.python.org/dev/peps/pep-0373/#update) as of January 2020. Most projects, including [TensorFlow](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0) and PyTorch, have dropped support for Python 2.

My preferred way to use a specific Python version is to create a [conda](https://docs.conda.io/en/latest/) environment. Once you have conda installed on your machine, I'd suggest running something like:

```bash
conda create -n haste
conda activate haste
conda install python==3.7
# run standard Haste installation process
```

**Comment by doubleapple123** [comment]
Thanks, I'll try this
