### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by bratao** [lmnt-com/haste#21]
Hello, 
I´m in awe with this library. I got great results with LayerNorm LSTM.

Do you have plans for releasing on pypi? With would allow more users to use it!

**Comment by sharvil** [comment]
That's great news, @bratao! I love hearing about what worked / didn't work.

I looked into releasing on PyPI before and it seems like there's a lot of work involved building for different Python, TF, and PyTorch versions. So yes, I'd like to release on PyPI but I could use some help from the community in getting there.

**Comment by sharvil** [comment]
I've uploaded source packages to PyPI. It's not as convenient as having pre-built binaries but it's a step forward. I've added instructions to the README as well. In short,

```
pip install haste_pytorch
pip install haste_tf
```

will download, build, and install Haste for PyTorch / TensorFlow.
