### ISSUE TITLE
Multiple Layers LSTM

### ISSUE THREAD

**Issue by dgwarlug47** [lmnt-com/haste#25]
I really wanted to use the Haste API in order to do a multiple layer LSTM. But I realized that, in order to do so you need the intermediate hidden states of a previous layer in order to feed the next layer, and I see no trivial solution for the problem with the support of your API. I wonder how the haste community of developers deals with multiple layers of LSTM.
Thank you so much for your time, and have a nice day.

**Comment by sharvil** [comment]
If you're using PyTorch, you can set `return_state_sequence=True` when you construct any RNN layer. The TensorFlow API doesn't have a mechanism to get the full intermediate states.

Are you using TensorFlow or PyTorch?

**Comment by dgwarlug47** [comment]
Pytorch. Thanks.

Em sex, 7 de ago de 2020 1:39 PM, Sharvil Nanavati <notifications@github.com>
escreveu:

**Comment by JCBrouwer** [comment]
Sorry if this is a dumb question, but how exactly does `return_state_sequence=True` allow you to construct a multi-layer LSTM? It seems that LSTM layers don't accept a state sequence, only a single state.
