### ISSUE TITLE
How to expose LayerNormGRUCell to python ?

### ISSUE THREAD

**Issue by thegodone** [lmnt-com/haste#32]
Is there a way to expose LayerNormGRUCell Cuda into python ?

**Comment by sharvil** [comment]
LayerNormGRU takes an initial state so maybe you can just keep sending in sequences of length 1 and track the state yourself. Does something like the following code work for you?

```python
x = torch.randn([seq_len, batch_size, channels])
gru = LayerNormGRU(...)

state = None
for i in range(seq_len):
  output, state = gru(x[i:i+1], state)
  # do something with `output`
```

This approach won't be as fast as running the GRU layer over the entire sequence in a single shot, but it'll run on GPU and give you equivalent results.

**Comment by thegodone** [comment]
it works thanks
