### ISSUE TITLE
 layer_norm_gru_cell

### ISSUE THREAD

**Issue by PatReis** [lmnt-com/haste#37]
In the layer_norm_gru_cell.py in build() for tf-version 2.3 and 2.5:

`self.gamma = v1.get_variable('gamma', initializer=v1.initializers.ones())`

is throwing an error

> The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.

Is it necessary to add a shape=1 to the get_variable call()?

**Comment by sharvil** [comment]
I'm happy to accept patches that fix issues with TF compatibility. In this particular case, it seems that the TF team broke backwards compatibility in a minor release.
