### ISSUE TITLE
Feature request for cell classes for pytorch

### ISSUE THREAD

**Issue by hadaev8** [lmnt-com/haste#42]

**Comment by JohnGiorgi** [comment]
I was also looking for cell classes and I found them here: `https://github.com/lmnt-com/haste/blob/master/docs/tf/haste_tf.md`

**Comment by hadaev8** [comment]
Isnt it tensorflow?

**Comment by JohnGiorgi** [comment]
@hadaev8 Sorry. I just noticed that and updated my comment.

**Comment by sharvil** [comment]
You can get the equivalent of running a single cell by passing in sequences of length one. See https://github.com/lmnt-com/haste/issues/32#issuecomment-853589015 for an example.

**Comment by JohnGiorgi** [comment]
Great, that looks like what I need.

I am just unsure how I reset the context in between batches?

**Comment by JohnGiorgi** [comment]
Great, that looks like what I need.

I am just unsure about how to clear the RNNs context in between calls to `forward`?

**Comment by hadaev8** [comment]
@sharvil shouldn't it be slower?

**Comment by sharvil** [comment]
Yes, it'll be slower because we can't fuse operations across time steps. That's the price you have to pay for using an RNN cell instead of providing the whole input in one shot.
