### ISSUE TITLE
Support for PyTorch packed sequences

### ISSUE THREAD

**Issue by joeylitalien** [lmnt-com/haste#46]
It seems like Haste does not support packed sequences for dealing with variable-length sequences in PyTorch. Any chance this gets implemented in the near future? Thanks for the great work.

**Comment by sharvil** [comment]
Thanks for the feedback, @joeylitalien. It's really unlikely that we'll support packed sequences unless someone from the community contributes it. But Haste does support padded sequences so maybe you could [do a conversion](https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pad_packed_sequence.html) if your code is carrying packed sequences around.

**Comment by joeylitalien** [comment]
I might be able to work something out; otherwise it's not big deal. Thanks!
