### ISSUE TITLE
[Feature] Windows build support

### ISSUE THREAD

**Issue by OverLordGoldDragon** [lmnt-com/haste#5]
[Logs](https://pastebin.com/RWNVqn4f); the ultimate error reads:

```
process_begin: CreateProcess(NULL, ar -crv libhaste.a lib/*.o, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [haste] Error 2
```

Any suggestions or alternate install methods? Don't know which "file" isn't found -- thanks.

<hr>

**Details**:

 - First it complained of cl.exe, so I added to PATH `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\"` where cl.exe is
 - Using [GNU Make 3.81](http://gnuwin32.sourceforge.net/packages/make.htm) -- Win 10 -- Windows SDK 10.0 -- VSC 2017 & 2019
 - Have CUDA 10.1, cuDNN 7.6
 - Ran `cd path_to_haste; make haste_tf` in `Anaconda Powershell Prompt` virtualenv

**Comment by sharvil** [comment]
Looks like you're missing `ar`, the GNU archiver, to build static libraries. Of course, that's expected since you're on Windows and compiling with MSVC. You might have better luck with a GNU toolchain (Cygwin) but I haven't tried it myself.

I think your options for running Haste are:
  - use Cygwin to build the code or;
  - figure out the command line flags to build Haste with MSVC or;
  - use a Linux machine

I don't have access to a Windows machine but I'm happy to answer any build questions to try and get this working on Windows.

**Comment by OverLordGoldDragon** [comment]
Got Cygwin x86_64 w/ `make` (Devel), same error log; debugging such builds, esp. between operating systems, can get involved. Is there a planned Windows support?

**Comment by sharvil** [comment]
You're going to need at least [`binutils`](https://cygwin.com/packages/summary/binutils.html) and  [`g++`](https://cygwin.com/packages/summary/gcc-g++.html) to build with the provided Makefile. You'll also need a CUDA installation in `/usr/local/cuda`. I'm not sure where CUDA dev files get installed to on Linux but you can always edit the Makefile to point to the right spot.

We'd love to support Windows but we honestly don't have a timeline for it.

**Comment by OverLordGoldDragon** [comment]
Thanks for the info, a followup: installed stuff, image below. On pathing, am unfamiliar with syntax - e.g. `-I/usr` for `LOCAL_CFLAGS` - what's the `-I`, or `-L`? Can I use absolute paths instead?

<hr>

![image](https://user-images.githubusercontent.com/16495490/76682995-f478e280-6619-11ea-8523-1f09474c0dbb.png)

**Comment by sharvil** [comment]
I have some good news and some bad news. The good news is that I was able to get Haste running on Windows with PyTorch. The bad news is that TensorFlow doesn't support Cygwin, and its custom op support on Windows is nothing short of an [unmitigated](https://github.com/tensorflow/tensorflow/issues/22240) [disaster](https://github.com/tensorflow/tensorflow/issues/27697).

To answer your questions, `-I` specifies the header/include path and `-L` specifies the library/link path. You can repeat those flags to specify multiple directories.

**Comment by OverLordGoldDragon** [comment]
@sharvil Not too surprised on TF; bit on tangent, how is Pytorch with custom functionality? I've been implementing optimizers and layers in `tf.keras`, and often come across what seem to be  backend limitations that unnecessarily complicate or even prohibit functionality. 

On the flags - any reference material you can point to? Still unclear, unsure how to look it up. (Alternatively: will simply replacing paths w/ their absolute path counterparts without touching the flags do it?) And on the install - guess it's go Linux or go Pytorch.

**Comment by sharvil** [comment]
I don't have a ton of experience with PyTorch, so take my experience with a grain of salt (all of our models are in TF). I've found custom op integration to be quite straightforward. The entire Haste <-> PyTorch integration took ~1 work day for someone with limited prior knowledge. I wish I could say the same about TensorFlow. The code in `frameworks/pytorch` and `frameworks/tf` in this repository demonstrate how drastically different the two frameworks are. PyTorch has a usable Python API and a usable C++ API. I think one could argue that TF has a mostly usable Python API (buggy as it may be) but it certainly doesn't have a usable C++ API. I've not felt limited by PyTorch's extensibility.

As for compiler flags, your best bet are the [gcc man page](http://man7.org/linux/man-pages/man1/gcc.1.html) and [option summary](https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html). There are a lot of flags. You can use absolute paths, but I don't think that will get you to a working `haste_tf` build on Windows. I've spent quite a bit of time trying to get it built to no avail.

**Comment by OverLordGoldDragon** [comment]
Tried `make haste_pytorch` with modified paths, also removed `-std=c++11` flags; build log:

<details>
  <summary>Click to expand</summary>

```
$ make haste_pytorch
nvcc -arch=sm_60 -c lib/lstm_forward_gpu.cu.cc -o lib/lstm_forward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/lstm_backward_gpu.cu.cc -o lib/lstm_backward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/gru_forward_gpu.cu.cc -o lib/gru_forward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
gru_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
gru_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
gru_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/gru_backward_gpu.cu.cc -o lib/gru_backward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
gru_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
gru_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
gru_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/layer_norm_forward_gpu.cu.cc -o lib/layer_norm_forward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
layer_norm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/layer_norm_backward_gpu.cu.cc -o lib/layer_norm_backward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
layer_norm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/layer_norm_lstm_forward_gpu.cu.cc -o lib/layer_norm_lstm_forward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
layer_norm_lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_lstm_forward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
nvcc -arch=sm_60 -c lib/layer_norm_lstm_backward_gpu.cu.cc -o lib/layer_norm_lstm_backward_gpu.o -x cu -Xcompiler -fPIC -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
layer_norm_lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
layer_norm_lstm_backward_gpu.cu.cc
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
ar -crv libhaste.a lib/*.o
r - lib/gru_backward_gpu.o
r - lib/gru_forward_gpu.o
r - lib/layer_norm_backward_gpu.o
r - lib/layer_norm_forward_gpu.o
r - lib/layer_norm_lstm_backward_gpu.o
r - lib/layer_norm_lstm_forward_gpu.o
r - lib/lstm_backward_gpu.o
r - lib/lstm_forward_gpu.o
/bin/sh: /cygdrive/c/Users/OverL/AppData/Local/Microsoft/WindowsApps/python: Permission denied
make: *** [Makefile:47: haste_pytorch] Error 126
```

</details>

```
LOCAL_CFLAGS := -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -Ilib -O3
LOCAL_LDFLAGS := -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64" -L. -lcudart -lcublas
```

Do the path flags look correct? Also, the permission denied file is [0KB](https://user-images.githubusercontent.com/16495490/77719844-beffcc00-6fff-11ea-8901-4e7529ba5b67.png); am I supposed to specify Pythonpath somewhere (`PYTHON ?= python`)? Or easier, a Windows version Makefile you could share?

**Comment by sharvil** [comment]
I've updated the Makefile to support PyTorch on Windows in addition to Linux. You'll need to run `make haste_pytorch` in a Cygwin shell. Other targets, e.g. `examples`, `benchmarks`, `haste_tf`, don't build with the supplied Makefile but this should be enough to get you started with PyTorch on Windows. Details about which software packages you need are in the commit message. Let me know if you run into any issues getting it built and running.

**Comment by OverLordGoldDragon** [comment]
@sharvil Great, thanks; ran it in Cygwin with administrative privileges, think it was actually building stuff for a few minutes, but terminated with an error:

<details>
  <summary>Logs</summary>


> $ make haste_pytorch
nvcc -arch=sm_60 -c lib/lstm_forward_gpu.cu.cc -o lib/lstm_forward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
lstm_forward_gpu.cu.cc                                                          nvcc -arch=sm_60 -c lib/lstm_backward_gpu.cu.cc -o lib/lstm_backward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
lstm_backward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/gru_forward_gpu.cu.cc -o lib/gru_forward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
gru_forward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/gru_backward_gpu.cu.cc -o lib/gru_backward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
gru_backward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/layer_norm_forward_gpu.cu.cc -o lib/layer_norm_forward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
layer_norm_forward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/layer_norm_backward_gpu.cu.cc -o lib/layer_norm_backward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
layer_norm_backward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/layer_norm_lstm_forward_gpu.cu.cc -o lib/layer_norm_lstm_forward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
layer_norm_lstm_forward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/layer_norm_lstm_backward_gpu.cu.cc -o lib/layer_norm_lstm_backward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
layer_norm_lstm_backward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/indrnn_backward_gpu.cu.cc -o lib/indrnn_backward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
indrnn_backward_gpu.cu.cc
nvcc -arch=sm_60 -c lib/indrnn_forward_gpu.cu.cc -o lib/indrnn_forward_gpu.o -x cu -Xcompiler "/MD" -I/usr/include/eigen3 -I/usr/local/cuda/include -Ilib -O3
indrnn_forward_gpu.cu.cc
lib /nologo /out:haste.lib lib/*.o
/bin/sh: /cygdrive/c/Users/OverL/AppData/Local/Microsoft/WindowsApps/python: Permission denied
make: *** [Makefile:64: haste_pytorch] Error 126

</details>

Again the same 0KB python file:

<img src="https://user-images.githubusercontent.com/16495490/78355933-ab380500-75bf-11ea-89b8-7a79c89fb0cd.png" width="550">

Should I direct it to a working python.exe (say, one in a conda virtual env) - and if so, how?

**Comment by sharvil** [comment]
Yes, you need a working python in your path. First, find out where your working python.exe is and then in your Cygwin shell:

```bash
export PATH="$PATH:/cygdrive/c/directory/containing/python/"
make haste_pytorch
```

`C:` gets replaced by `/cygdrive/c` and backslashes `\` get converted to forward slashes `/`. For example, suppose the path to a working Python is `C:\Users\<username>\AppData\Local\Programs\Python\Python37\python.exe`. Then your PATH would get exported like this:
`export PATH="$PATH:/cygdrive/c/Users/<username>/AppData/Local/Programs/Python/Python37"`

**Comment by sharvil** [comment]
I don't see any compile-time errors in the log file or in what you've pasted. They're all warnings (which, BTW, I also get on Windows). Did it produce the `haste_pytorch*.whl` file after running make? Looks to me like it succeeded.

You don't need to do any manual cleanup. The Makefile doesn't reuse any cached/intermediate files so you get a clean build every time. Your PATH export looks good to me.

**Comment by OverLordGoldDragon** [comment]
At last, the stars have aligned - SUCCESS. I may be learning Pytorch just for the sake of this library.

Thanks for following through with this to the end - should also serve useful for others. Might want to summarize this thread's info somewhere, also Stateful in Pytorch's - other than that, feel free to close.

<hr>

My specific steps for reference, not listed in [commit instructions](https://github.com/lmnt-com/haste/commit/bcd482482d96d7224a103e503bf9c741cfcb9d4d):

 - `export PATH="$PATH:/cygdrive/d/Anaconda/envs/pyt"` (`pyt` == Anaconda virtual env)
 - `pip install haste_pytorch --no-index --find-links "C:\stuff\haste-master"`

**Comment by sharvil** [comment]
Excellent! I'm glad you were able to get up and running on Windows. I'll document what we learnt here on the wiki.

**Comment by huangkeju** [comment]
Hi, I'm also trying to build haste_pytorch on windows. I followed the instructions of [https://github.com/lmnt-com/haste/commit/bcd482482d96d7224a103e503bf9c741cfcb9d4d](url) but when I run 'make haste_pytorch' I got the following error:

`LINK : fatal error LNK1181: 无法打开输入文件“haste.lib”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.270
23\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
make: *** [Makefile:73: haste_pytorch] Error 1

`
Any suggestions?

**Comment by kotlyar-shapirov** [comment]
Hi from the 2023! New year, same issues :)
Same issue as [huangkeju](https://github.com/huangkeju) got, link.exe cannot open input file haste.lib
Installing the latest version haste 0.5.0-rc0
All the rest is done per instructions (Cygwin, exporting path to python from anaconda folder).

Any help would be much appreciated
