### ISSUE TITLE
[Pytorch] Pass in hidden and cell state in forward pass?

### ISSUE THREAD

**Issue by sosuperic** [lmnt-com/haste#6]
Is it possible to pass in the hidden and cell state to the (LayerNorm)LSTM's forward pass? To be clear:

```
y, state = norm_lstm_layer(x)    # current API
y, state = norm_lstm_layer(x, (h0, c0))  # desired API, also same as nn.LSTM's API
```
Maybe I'm missing something because it seems like a pretty standard use case. For example,
1. At inference time, I am decoding one time step at a time (in order to use the previous output as the current input). That means I need to pass in the last hidden and cell state as well.
2. Initializing the LSTM with some representation.

Thanks! And this looks great btw; I've had many annoyances having to implement custom rnn's (layer norm, recurrent dropout, etc.) in pytorch in the past.

**Comment by sharvil** [comment]
You're not missing anything – there was no initial state argument to the RNN layers. I've submitted a change allows you to do it now. You can specify `(h0, c0)` for LSTM and LayerNormLSTM layers as you did above, or `h0` for GRU cells.

Thanks for the feedback! It's much appreciated.

**Comment by sosuperic** [comment]
Awesome, thanks!
