### ISSUE TITLE
README PyTorch example

### ISSUE THREAD

**Issue by nimz** [lmnt-com/haste#9]
This is minor, but the three PyTorch layers defined in the README should be put on the GPU, e.g.

`norm_lstm_layer = haste.LayerNormLSTM(input_size=128, hidden_size=256, zoneout=0.1, dropout=0.05).cuda()`

since the input is a CUDA tensor.

**Comment by sharvil** [comment]
Thanks so much for pointing this out, @nimz. Fixed!
